name: Lint
on:
  pull_request:
    branches: 13.0
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-python@v2.1.3
        with:
          python-version: 3.6
      - uses: actions/cache@v2.1.2
        id: cache-pre-commit
        with:
          path: ~/.cache/pre-commit
          key: cache-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v2.0.0
